### ISSUE TITLE
how to run this model

### ISSUE THREAD

**Issue by Utkarsh-Utsav** [reachsumit/deep-unet-for-satellite-image-segmentation#1]
can you tell me how i can run this ? What dependencies it require ?

**Comment by reachsumit** [comment]
This project was run as a job on HPC using Slurm. The code for that script is in "run.sbatch" file. You can always just run the train_unet.py followed by predict.py directly.

Also, you'll need numpy, tifffile, keras apart from the native Python packages such as random, math, matplotlib.

**Comment by Utkarsh-Utsav** [comment]
Thank for your response. I am student trying to learn similar thing. I tried training this on my system and this would take more than month. If possible could you provide me your pretrained weight.

**Comment by reachsumit** [comment]
I don't quite remember if I made some changes and re-ran the code after posting the code here. But this is the latest weight file that I have on my space at GPU cluster. Good luck!  https://drive.google.com/file/d/1fVE0cDtYgIJKsPe43zeODX0-_4pzQOU_/view?usp=sharing
