### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Tangtyone** [reachsumit/deep-unet-for-satellite-image-segmentation#10]
![default](https://user-images.githubusercontent.com/35962229/53574301-4d5e1000-3baa-11e9-80cf-9e41f71af57c.png)
Hello, this error occurs when I run the train_unet.py file. But I don't know how to modify it, can you help me? thank you very much.

**Comment by reachsumit** [comment]
That's a memory error. Use smaller batch size or more GPU memory.
