### ISSUE TITLE
i want to know how to download the pretrain weight "unet_weights.hdf5"

### ISSUE THREAD

**Issue by DecaiJin** [reachsumit/deep-unet-for-satellite-image-segmentation#16]
hello body ,it's same to the title .In the code,i think it's essential to load the pretrain weight,but i don't know where i can download the weight .i hope receive your answer. Thanks !

**Comment by prativadas** [comment]
https://drive.google.com/file/d/1fVE0cDtYgIJKsPe43zeODX0-_4pzQOU_/view?usp=sharing 
this is the link given by him in the closed issue section.

**Comment by redbooks-jdc** [comment]
> https://drive.google.com/file/d/1fVE0cDtYgIJKsPe43zeODX0-_4pzQOU_/view?usp=sharing
> this is the link given by him in the closed issue section.

**Comment by Sadia-Khan-Rupa** [comment]
after using this weight this error shows "ValueError: You are trying to load a weight file containing 36 layers into a model with 19 layers." Can anyone give a solution?
