### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by vaibhav198** [reachsumit/deep-unet-for-satellite-image-segmentation#2]
could you tell me which satellite used or could you give me the dataset link ?

**Comment by reachsumit** [comment]
Dataset is from SpaceNet Challenge (https://spacenetchallenge.github.io/), and was originally collected from DigitalGlobe’s WordView-2 and WorldView-3 satellites. Data present in this repo contains only a few images from SpaceNet dataset. You will have to get the data from AWS.

Read my article for more details on the dataset, and how to download it.
https://medium.com/@sumit.arora/getting-started-with-aws-spacenet-and-spacenet-dataset-visualization-basics-7ddd2e5809a2

**Comment by prativadas** [comment]
hi, as I can see in the link of spacenet dataset it is only for the task of building and road segmentation and detection. how did you get the labels for 5 classes?
