### ISSUE TITLE
Training with the given U_net model gives very small probability values

### ISSUE THREAD

**Issue by mijo2** [reachsumit/deep-unet-for-satellite-image-segmentation#7]
Hello there. I took your U_net model and applied similar idea to train my own model which takes 4 channel input with channels being RGB(NIR) and output being of 8 classes.
When I trained my own model, it gave me very inaccurate values which predicted classes only at the boundaries of the images and that too with very small values the maximum probability being in order of 1e-15.

Can you give me some of your insights or suggestions regarding this issue? Is the problem with the model or maybe its regarding an inaccurate way of pre processing applied?

**Comment by reachsumit** [comment]
It's pretty standard implementation. There can be dozens of reasons why your model didn't converge. Reading the original paper should help.
