### ISSUE TITLE
What is PATCH_SZ(Patch size) and TRAIN_SZ(number of patches) used in the train_unet.py file?

### ISSUE THREAD

**Issue by s-shikharcse** [reachsumit/deep-unet-for-satellite-image-segmentation#8]
When I am running this code with own geospatial dataset of 1500 X 1500 resolution. It's throwing error. How to decide the value of patch size?

**Comment by reachsumit** [comment]
You will have to customize layer dimensions based on your need. Study the UNet architecture.
