### ISSUE TITLE
how to show the data?

### ISSUE THREAD

**Issue by swpucl** [reachsumit/deep-unet-for-satellite-image-segmentation#9]

**Comment by HetSP07** [comment]
I think you can use this code https://github.com/ternaus/kaggle_dstl_submission/blob/master/src/visualize.py

**Comment by reachsumit** [comment]
You can use tifffile to display image in an interactive environment like Jupyter notebooks. You may want to use just the RGB bands depending on your case. And, you could also colorize the outcomes like this: https://github.com/reachsumit/deep-unet-for-satellite-image-segmentation/blob/master/predict.py#L47.

**Comment by swpucl** [comment]
> You can use tifffile to display image in an interactive environment like Jupyter notebooks. You may want to use just the RGB bands depending on your case. And, you could also colorize the outcomes like this: https://github.com/reachsumit/deep-unet-for-satellite-image-segmentation/blob/master/predict.py#L47.

Thank you for your advice.But now I can only show grayscale images.my code like this:
img = tiff.imread('test.tif')
tiff.imsave('result.tif', img.astype('uint8'))
